### ISSUE TITLE
Example(s)

### ISSUE THREAD

**Issue by andreww** [earall/seismic_melts#2]
Some kind of worked example would be good. This is probably best in the form of a script that will generate a figure from the G^3 paper. This means you'll also need to ship some data. Try and pick a small file.

**Comment by earall** [comment]
SeismicMelts.m script runs through calculation of seismics to produce a 3D tensor plot of seismic properties or values for seismic properties in X, Y or Z directions.
The script flow chart is shown below.

![functionflowchart](https://user-images.githubusercontent.com/10488022/53185704-705f5180-35f7-11e9-94b2-67acd8279fbb.png)
