### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by andreww** [earall/seismic_melts#4]
Two things to consider:

* Are the names of `surface_wave` and `surface_waves` too similar?
* Is it worth putting the functions that make a tensor (`tensor_*`) together into a single function. This would be a possibility if they share the same API.

**Comment by earall** [comment]
Streamlining, the tensor_melt function covers the _iso, _shp, _bac and _cpo

The tensor_melt function includes a 'model' option to reduce the number of functions with similar names.
Surface_wave and surface_waves were removed in commit b29f41a.
